spring:
    jpa:
          hibernate:
              ddl-auto: update
          show-sql: true
          properties:
                hibernate.format_sql: false
                hibernate.enable_lazy_load_no_trans: true
          open-in-view: true
    datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/spring_quartz?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: 123

          type: com.alibaba.druid.pool.DruidDataSource
          dbcp2:
                min-idle: 5
                initial-size: 5
                validation-query: select 1
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                pool-prepared-statements: true